//file: System-Design-with-Python-and-K8s/python/src/rabbit/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP  # Internal-only service, not exposed outside the cluster
  selector:
    app: rabbitmq  # Matches pods with label app=rabbitmq
  ports:
    - name: http  # RabbitMQ management UI (default port: 15672)
      protocol: TCP #RabbitMQ needs TCP for the actually sending and receiving of messages

      port: 15672  # This Service exposes RabbitMQ's HTTP management UI (port 15672) internally.
                   # The Ingress resource references this Service to route external HTTP traffic to the UI.
                   # Without this Service, the Ingress controller cannot forward requests to the correct pod.
                   
      targetPort: 15672
    - name: amqp  # AMQP : RabbitMQ messaging protocol (default port: 5672)
      protocol: TCP
      port: 5672
      targetPort: 5672
